### ISSUE TITLE
Question: Setup at the pytest session level

### ISSUE THREAD

**Issue by stevenheidel** [CloverHealth/pytest-pgsql#9]
I'd like to do some setup of a database (for instance adding all the tables) once, it seems expensive to do this with every test even using transacted_postgresql_db. Is there a way to do this initial setup of schemas only once? I tried adding postgresql_db to a pytest.fixture with session scope but postgresql_db has function level scope so I was unsure how to proceed.

**Comment by dargueta** [comment]
http://pytest-pgsql.readthedocs.io/en/latest/#customizing-database-fixtures
